sudo: required

services:
  - redis-server

matrix:
  include:
    - language: node_js
      node_js: 8.8
      env: TEST=FRONTEND_UNIT
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        directories:
          - frontend/node_modules
    - language: python
      python: 3.5
      env: TEST=INTEGRATION
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        pip: true
        directories:
          - frontend/node_modules
    - language: python
      python: 3.5
      env: TEST=BACKEND_UNIT
      cache:
        pip: true

before_install: ./util/ci.sh before_install
install: ./util/ci.sh install
before_script: ./util/ci.sh before_script
script: ./util/ci.sh script
after_success: ./util/ci.sh after_success
