sudo: required

matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip: true
      install:
        - pip install django coverage coveralls
      before_script:
        - export PROJECT_PATH=$(pwd)/backend/backend
        - python3 util/secret-key-gen.py
      script:
        - coverage run --branch --source="./backend/api,./backend/websocket" ./backend/manage.py test
      after_success:
        - coveralls

    - language: node_js
      node_js: 8.8
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        npm: true
        directories:
          - frontend/node_modules
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - cd frontend
      install:
        - npm install
        - npm install coveralls
      script:
        - npm run test -- --code-coverage --watch false
        - npm run e2e
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js ..
      after_script:
        - cd ..
